### ISSUE TITLE
Documentation is not enough for running inference

### ISSUE THREAD

**Issue by summersonnn** [UARK-AICV/AerialFormer#1]
Hi. I followed the installation steps and I'm ready to do inference. My aim is not to train a model but to use an existing model on my image(s).

`python tools/test.py work_dirs/aerialformer_tiny_512x512_loveda/2023_0101_0000/aerialformer_tiny_512x512_loveda.py work_dirs/aerialformer_tiny_512x512_loveda/2023_0101_0000/latest.pth --eval mIoU`

This is in the Readme file but I don't get it. We did not download any weight file yet we're giving it in the parameter. The paths also confuse me. Can you clarify how to do inference please?

**Comment by thanyu-hub** [comment]
The 'work_dir' specifies the directory where your experimental logs, configuration files, and model weights are stored. If you are using Docker, you should bind this directory to your current directory to ensure it can be accessed within the Docker environment.
Also, the checkpoints are obtained in the model directory (like aerialformer_tiny_512x512_loveda) only after you run the training. Since we have not published any pre-trained weights, you will need to train the model first before performing inference. Make sure to complete the training to generate the necessary weight files for inference.

**Comment by aleksmirosh** [comment]
Hi guys,
thank you for sharing your code.
do you have plans to share weights? i am just thinking should I wait or try to train
